version: '3'
services:
  nginx:
    container_name: yourwish-nginx
    build: ./
    volumes:
    - ./templates:/etc/nginx/templates
    - ./logs:/var/log/nginx/logs
    - ./init.sh:/init.sh
    ports:
    - "8080:80"
    environment:
    - NGINX_HOST=yourwish.gifts
    - NGINX_PORT=80