version: '3'
services:
  nginx:
    container_name: yourwish-nginx
    build: ./
    volumes:
    - ./code/templates:/etc/nginx/templates
    - ./code/logs:/var/log/nginx/logs
    - ./code/init.sh:/init.sh
    ports:
    - "80:80"
    - "443:443"
    environment:
    - NGINX_HOST=localhost
    - NGINX_PORT=80