version: '3'
services:
  nginx:
    container_name: my-nginx
    build: ./
    volumes:
    - ./code/templates:/etc/nginx/templates
    - ./code/logs:/var/log/nginx/logs
    - ./code/docker_run.sh:/docker_run.sh
    ports:
    - "80:80"
    - "443:443"
    environment:
    - NGINX_HOST=localhost
    - NGINX_PORT=80