version: '3'
services:
  nginx:
    container_name: my-nginx
    build: ./nginx
    volumes:
      - ./nginx/code/templates:/etc/nginx/templates
      - ./nginx/code/logs:/var/log/nginx/logs
      - ./nginx/code/run.sh:/run.sh
    command: /bin/bash /run.sh
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    depends_on:
      - db
  db:
    container_name: my-db
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  server:
    container_name: my-server
    build: ./django
    command: python manage.py runserver 0.0.0.0:8000 --insecure
    volumes:
      - ./django/code:/code
    ports:
      - "8088:8088"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    env_file:
      - ./django/code/.env
    depends_on:
      - db