# Generated by Django 3.2.16 on 2023-01-30 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_seq', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(default='-', max_length=58)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DjangoUser',
            fields=[
                ('django_user_seq', models.AutoField(primary_key=True, serialize=False)),
                ('auth_user_seq', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('user_seq', models.ForeignKey(db_column='user_seq', on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
            options={
                'db_table': 'djangoUsers',
                'managed': True,
            },
        ),
    ]
