FROM ubuntu:18.04

WORKDIR /

RUN apt-get update && apt-get install -y \
    iputils-ping \
    curl \
    net-tools
#     vim

#COPY . .

#ENV VAR_NAME=value

# Define the command to run when the container starts
CMD [ "bin/bash" ]
